apiVersion: v1
kind: Service
metadata:
  name: spring-cashier-worker-service
spec:
  type: ClusterIP
  selector:
    app: spring-cashier-worker
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
