
version: "3"

services:
  redis:
    image: redis
    platform: linux/amd64
    networks:
      - network
    ports:
      - 6379
    restart: always
  mysql:
    image: mysql:8.0
    platform: linux/amd64
    volumes:
      - /tmp:/tmp
    networks:
      - network
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: "cool"
    restart: always
  cashier:
    image: spring-cashier
    platform: linux/amd64
    depends_on:
      - mysql
    networks:
      - network
    ports:
      - "9090:8080"
    environment:
      MYSQL_HOST: "mysql"
      MYSQL_USER: "quang"
      MYSQL_PW: "chu"
      REDIS_HOST: "redis"
      REDIS_PASSWORD: "foobared"
      REDIS_PORT: "6379"
      API_KEY: "2H3fONTa8ugl1IcVS7CjLPnPIS2Hp9dJ"
      API_HOST: "kong:8000/api"
    restart: always
  lb:
    image: eeacms/haproxy
    platform: linux/amd64
    depends_on:
      - cashier
    ports:
      - "80:5000"
      - "1936:1936"
    environment:
      BACKENDS: "cashier"
      BACKENDS_PORT: "9090"
      DNS_ENABLED: "true"
      COOKIES_ENABLED: "false"
      LOG_LEVEL: "info"
    networks:
      - network

volumes:
  schemas:
    external: false

networks:
  network:
    driver: bridge

